### ISSUE TITLE
Saw systemd service (Linux)

### ISSUE THREAD

**Issue by gusarg81** [Joe-Klauza/sandstorm-admin-wrapper#108]
Hi, I case someone needs it, in my installation (Ubuntu focal), I've created saw.service for systemd:

> [Unit]
> Description=Sandstorm Admin Wrapper (SAW)
> After=network-online.target
> Wants=network-online.target
> 
> [Service]
> Type=idle
> ExecStart=/path/to/linux_start.sh
> StandardOutput=syslog
> StandardError=syslog
> SyslogIdentifier=saw
> 
> [Install]
> WantedBy=multi-user.target

And, in rsyslog conf folder (to separate log entry from syslog), in /etc/rsyslog.d/60-saw.conf:

> if $programname == 'saw' or $programname == 'InsurgencyServer-Linux-Shipping' then /var/log/saw.log
> & stop

This will create log in /var/log/saw.log

**Comment by Joe-Klauza** [comment]
Hi @gusarg81. Please only open issues for problems or direct questions. Helpful suggestions can go in the Discord linked in the README.md. Note we already have a systemd service example in the rpository.
