### ISSUE TITLE
Server without query port

### ISSUE THREAD

**Issue by sargolin** [Joe-Klauza/sandstorm-admin-wrapper#110]
I am not able to setup a server without a query port, so it is private, not known to the community and runs with XP - password protection would refuse that.

However, I am not sure if this actually works, since the scripts rely on query information.

Would it work still by blocking the port in the firewall or does that actually block the saw from working?

Thanks for any input on this
Madman

**Comment by Joe-Klauza** [comment]
Hi, @sargolin. I think you nailed the solution in your suggestion. SAW does indeed use the query information, so it would be a bit of a refactor to make it work without it; blocking it at the host or router firewall sounds perfect! Assuming SAW is running the server or running on the same machine, it would still be able to communicate.
