### ISSUE TITLE
steamclient.so missing in docker install

### ISSUE THREAD

**Issue by yay101** [Joe-Klauza/sandstorm-admin-wrapper#111]
[PID 76 Ports 7777,27131,27015] | dlopen failed trying to load:
[PID 76 Ports 7777,27131,27015] | steamclient.so
[PID 76 Ports 7777,27131,27015] | with error:
[PID 76 Ports 7777,27131,27015] | steamclient.so: cannot open shared object file: No such file or directory
[PID 76 Ports 7777,27131,27015] | dlopen failed trying to load:
[PID 76 Ports 7777,27131,27015] | /home/sandstorm/steamcmd/.steam/sdk64/steamclient.so
[PID 76 Ports 7777,27131,27015] | with error:
[PID 76 Ports 7777,27131,27015] | /home/sandstorm/steamcmd/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory

**Comment by Joe-Klauza** [comment]
Hi @yay101; this seems to be an issue with SteamCMD. One user on our Discord got it working with the following:

> I copied a steamclient.so to the location it was complaining about and got it working.

Hope this helps!
