### ISSUE TITLE
Issue with bundle install on Ruby 2.7.2+

### ISSUE THREAD

**Issue by Dr-D12345** [Joe-Klauza/sandstorm-admin-wrapper#112]
Running ./windows_start.bat on Windows with ruby 2.7.2 will result in:

`Could not find gem 'ruby  (< 2.7.dev, >= 2.2)', which is required by gem 'ffi',`

I fixed this by reverting ruby to 2.6.2. This is most likely caused by a problem with ffi instead of this repo, however wanted to highlight it in case anyone else came into the same issue.

**Comment by Joe-Klauza** [comment]
Thanks, @Dr-D12345. Next time I get to it I will see if we can upgrade some dependencies to fix this issue.
