### ISSUE TITLE
Did I crash the installation somehow?

### ISSUE THREAD

**Issue by sargolin** [Joe-Klauza/sandstorm-admin-wrapper#113]
I used SAW and deleted a couple of servers, reinstalled and stuff like that - so normal usage. But somehow I'm afraid I crahsed my installation. You ever seen anything like it - only appears when I clcik on "daemons" or "status" - all other links including login etc. working fine (the logs don't throw an error). Any ideas?

Oh, one thing - I had two instances of SAW open in my browser - is that an issue?

Error thrown on website:

An error occurred (NoMethodError). Only hosts can see the following message and backtrace: undefined method `config' for nil:NilClass | Backtrace:
~/saw/admin-interface/docroot/views/server-list.erb:3:in `block (2 levels) in singleton class'
~/saw/admin-interface/docroot/views/server-list.erb:3:in `each'
~/saw/admin-interface/docroot/views/server-list.erb:3:in `sort_by'
~/saw/admin-interface/docroot/views/server-list.erb:3:in `block in singleton class'
~/saw/admin-interface/docroot/views/server-list.erb:-6:in `instance_eval'
~/saw/admin-interface/docroot/views/server-list.erb:-6:in `singleton class'
~/saw/admin-interface/docroot/views/server-list.erb:-9:in `__tilt_70026323021000'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `evaluate'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:109:in `render'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:839:in `render'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:682:in `erb'
lib/webapp.rb:443:in `block (2 levels) in '
~/saw/admin-interface/docroot/views/server-status.erb:6:in `block in singleton class'
~/saw/admin-interface/docroot/views/server-status.erb:-6:in `instance_eval'
~/saw/admin-interface/docroot/views/server-status.erb:-6:in `singleton class'
~/saw/admin-interface/docroot/views/server-status.erb:-9:in `__tilt_70026323021000'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:170:in `evaluate'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tilt-2.0.9/lib/tilt/template.rb:109:in `render'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:839:in `render'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:682:in `erb'
lib/webapp.rb:442:in `block in '
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/httpserver.rb:140:in `service'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/httpserver.rb:96:in `run'
~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'

**Comment by sargolin** [comment]
Oh, and in "control" the active server dropdown does not show anything - althought the servers are all running.....

**Comment by sargolin** [comment]
Forget about it - a restart of the service on system level fixed it - I'l leave thought, it for you to notice and delete....

**Comment by Joe-Klauza** [comment]
Hi, @sargolin! Thanks for the report. I believe this is the same issue as #106. Will be resolved eventually!
