### ISSUE TITLE
SAW not working after restart and randomly not starting servers + no login possible

### ISSUE THREAD

**Issue by sargolin** [Joe-Klauza/sandstorm-admin-wrapper#114]
HI Joe, I have strange issues starting with v0.13.5 or 6. I didn't give it too much attention, but they are getting worse and I can't really tell you if it has to do with SAW or the surroundings (running on Linux Ubuntu 20 Server).

First, since a couple of weeks ago, it seemed that out in 9/10 SAW restarts (I do that every night for backup) one of my 4 INS Servers does not come back up. Can be any server, not a specific one. I have t hit restart the server in the morning and everything works. Than, since a couple of days, I wasn't able to login properly (Login failed).....I restarted SAW and it didn't work...had to bring back my backup from a couple of days before. Now, today SAW wasn't reachable by https. Service running...nothing. I restarted SAW and was able to login. But all servers went to half online....weren't reachable, no matter how often I restart them. So, again SAW restart and now I'm unable to login again. 

I know that this is all but a decent failure description, but I wanted to let you know, that something strange is happening since the changes in version 0.13.4, which ran beautifully.

Let me know, if I can do anything to help, or you want to have a look by yourself,

Best regards,
Oliver

**Comment by sargolin** [comment]
Can't login anymore, even after I restored the backup....any ideas?

```
2020-11-11 15:24:12 +0100 | ERROR   | SSL_accept returned=1 errno=0 state=error: http request
2020-11-11 15:24:12 +0100 | ERROR   | Backtrace:
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `accept'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `block (2 levels) in start_thread'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/utils.rb:263:in `timeout'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:297:in `block in start_thread'
2020-11-11 15:24:13 +0100 | ERROR   | SSL_accept returned=1 errno=0 state=error: http request
2020-11-11 15:24:13 +0100 | ERROR   | Backtrace:
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `accept'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `block (2 levels) in start_thread'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/utils.rb:263:in `timeout'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:297:in `block in start_thread'
2020-11-11 15:24:13 +0100 | ERROR   | SSL_accept returned=1 errno=0 state=error: http request
2020-11-11 15:24:13 +0100 | ERROR   | Backtrace:
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `accept'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `block (2 levels) in start_thread'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/utils.rb:263:in `timeout'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:297:in `block in start_thread'
2020-11-11 15:24:13 +0100 | ERROR   | SSL_accept returned=1 errno=0 state=error: http request
2020-11-11 15:24:13 +0100 | ERROR   | Backtrace:
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `accept'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `block (2 levels) in start_thread'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/utils.rb:263:in `timeout'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:297:in `block in start_thread'
2020-11-11 15:24:18 +0100 | ERROR   | SSL_accept returned=1 errno=0 state=error: http request
2020-11-11 15:24:18 +0100 | ERROR   | Backtrace:
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `accept'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `block (2 levels) in start_thread'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/utils.rb:263:in `timeout'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:297:in `block in start_thread'
2020-11-11 15:24:48 +0100 | ERROR   | execution timeout
2020-11-11 15:24:48 +0100 | ERROR   | Backtrace:
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `accept'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:299:in `block (2 levels) in start_thread'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/utils.rb:263:in `timeout'
  /home/inssserver/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:297:in `block in start_thread'


```

**Comment by sargolin** [comment]
Doesn't seem to have anything to do with it - I mean the above....after manually starting it again, I still can't login (Login failed) and no errors come up in the console.....before you ask - the credentials are saved in th ebrowser and they worked always - just retyped the pass, but nogo....don't know what to do atm, since I don't get any error messages I can work with - don't want to reinstall the entire things with my servers.....any help is appreciated

**Comment by Joe-Klauza** [comment]
Hi @sargolin. Not sure what is happening here; could be an SSL issue between the browser and application that I have not seen before. Per the `README.md` if you delete `admin-interface/config/users.json` and restart SAW you should be able to log in with the default credentials (`admin`/`password`). If this fails, maybe try another browser. I know Firefox does not like self-signed certificates.

**Comment by sargolin** [comment]
Thanks, that's exactly what I just found out - the user file was reset to standard.....I don't know why. However, after restarting and logging in with standard credentials, all looks fine. I have no idea what caused that, but I'll keep an eye on it and report back. So far, issue solved.....thanks for your help (BTW, I'm using Vivaldi and it doesn't have an issue with self signed certs

**Comment by sargolin** [comment]
Closed
