### ISSUE TITLE
Apache reverse proxy example settings

### ISSUE THREAD

**Issue by gusarg81** [Joe-Klauza/sandstorm-admin-wrapper#115]
Hi,

I've issued a new install of SAW in another server, but I would like to use Reverse Proxy approach using Apache2.

Any tip for the how? I wrote a simple proxy example (using http://mydomain.com/saw) but when I enter the URL it redirects to http://mydomain/login and of course error 404.

Thanks

**Comment by Joe-Klauza** [comment]
Hi, @gusarg81! I am not a networking expert, but I think you might want to use a subdomain for SAW, e.g. `saw.mydomain.com` instead of `mydomain.com/saw`. That should solve it! 🤞

**Comment by gusarg81** [comment]
Hi!

Well, no. I fact I not going to create a subdomain, because mydomain is already one (games.gdnet.ar) which I will move my home game server to that subdomain, thats why I wanted to setup in a location inside this subdomain.

Thanks anyway, I will do some test and post it here if works, for someone else if needed.

**Comment by Joe-Klauza** [comment]
Alright, sorry about that. Have you considered an additional subdomain (`saw.games.gdnet.ar`)? There might be DNS restrictions based on your provider; not sure how that works. I saw some other options [here](https://serverfault.com/a/561897) that might be useful.

**Comment by gusarg81** [comment]
Well, the DNS provider is me (is my server housed in a Datacenter, so I am migrating SAW from my Home server to there, which has dedicated connection).

Still the idea is like I said.

Yeah, but that approach is long. I Will try using ProxyPassMatch to catch everything.

**Comment by gusarg81** [comment]
I´ve forgot to close this.

> RequestHeader set X-Forwarded-Proto "https"
> RequestHeader set X-Forwarded-Port 443
> ProxyPreserveHost On
> ProxyPassMatch "^/((?!(?:errors|\.well-known)/acme-challenge/).*)" "http://127.0.0.1:51422/$1" retry=30 timeout=7200
> ProxyPassReverse "/" "http://127.0.0.1:51422/"

This for my case, using SSL in Apache.
