### ISSUE TITLE
Issues with ruby ... i guess

### ISSUE THREAD

**Issue by alphatonic** [Joe-Klauza/sandstorm-admin-wrapper#119]
I installed the ruby bundle and get this error when launching via the windows_start.bat

lib/webapp.rb:12:in `require': cannot load such file -- webrick (LoadError)

I already installed webrick via "gem install webrick".

I attached the entire content of the commandprompt when i try to launch it maybe it helps.

[log-Windows_Start_dot_bat.txt](https://github.com/Joe-Klauza/sandstorm-admin-wrapper/files/7224937/log-Windows_Start_dot_bat.txt)

**Comment by scaramunga** [comment]
I have run into the same problem. What was the solution?

**Comment by alphatonic** [comment]
It's been a while but i think what finally fixed it for me was a complete reinstall of ruby. Also restart your PC or at least logoff and login again so the environment variables that are changed by the installer are active.
