### ISSUE TITLE
Query status down

### ISSUE THREAD

**Issue by gusarg81** [Joe-Klauza/sandstorm-admin-wrapper#121]
I am not sure when this happen, but was working before update for sure.

In the SAW panel shows as "Query status: down", so my server does not show in Community servers list (which was working few days ago).

Tried to changed the port 3 times, always shows "Query status: down".

Now, on terminal I check that query port is up, but telnet test fails:

> sudo netstat -tulpn | grep 27215
> udp        0      0 0.0.0.0:27215           0.0.0.0:*                           302837/InsurgencySe
> 
> telnet 127.0.0.1 27215
> Trying 127.0.0.1...
> telnet: Unable to connect to remote host: Connection refused

Server is running in Ubuntu server 20.04.

[f7ba6e0f-8755-42c3-9a87-1ba042b30891.log](https://github.com/Joe-Klauza/sandstorm-admin-wrapper/files/7697774/f7ba6e0f-8755-42c3-9a87-1ba042b30891.log)

**Comment by gusarg81** [comment]
Weird, I just configured all my server from Scratch with same settings and Query status is OK now.

**Comment by gusarg81** [comment]
Ok, It happened again. Log from SAW start (linux-start.sh):

> 
> 2021-12-11 21:50:20 -0300 | INFO    | [PID 389141 Ports 27015,27016,27117] | Game process spawned. Starting self-monitoring after detecting RCON listening message.
> 2021-12-11 21:50:33 -0300 | INFO    | [PID 389141 Ports 27015,27016,27117] | RCON listening. Waiting for Server Query success before ending server lock
> 2021-12-11 21:50:40 -0300 | ERROR   | Error while sending RCON | Exception occurred (RuntimeError): 127.0.0.1:27117       Nil response for RCON.
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:228:in `send_receive'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:206:in `block in send_receive_wrapper'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:203:in `send_receive_wrapper'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:326:in `send'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:358:in `get_players_and_bots'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:266:in `do_rcon_query'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:352:in `block (4 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:352:in `block (3 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:348:in `block (2 levels) in monitor'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `loop'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `block in monitor'
>   ~/Apps/saw/admin-interface/ext/thread.rb:13:in `block in initialize'
> 2021-12-11 21:50:40 -0300 | ERROR   | 127.0.0.1:[27016,27117] Monitor | RCON query failed | Exception occurred (RuntimeError): 127.0.0.1:27117       Nil response for RCON.
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:228:in `send_receive'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:206:in `block in send_receive_wrapper'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:203:in `send_receive_wrapper'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:326:in `send'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:358:in `get_players_and_bots'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:266:in `do_rcon_query'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:352:in `block (4 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:352:in `block (3 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:348:in `block (2 levels) in monitor'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `loop'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `block in monitor'
>   ~/Apps/saw/admin-interface/ext/thread.rb:13:in `block in initialize'
> 2021-12-11 21:50:40 -0300 | WARN    | 127.0.0.1:[27016,27117] Monitor | Time since last RCON success: 7s
> 2021-12-11 21:50:44 -0300 | WARN    | [127.0.0.1:27016] Couldn't get UDP response (NoUDPResponseError raised)
> 2021-12-11 21:50:44 -0300 | ERROR   | 127.0.0.1:[27016,27117] Monitor | Server query failed | Exception occurred (NoUDPResponseError): Could not read a UDP response from server 127.0.0.1:27016
>   ~/Apps/saw/admin-interface/lib/server-query.rb:28:in `send_recv_udp'
>   ~/Apps/saw/admin-interface/lib/server-query.rb:26:in `send_recv_udp'
>   ~/Apps/saw/admin-interface/lib/server-query.rb:42:in `a2s_info'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:298:in `do_server_query'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:355:in `block (4 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:355:in `block (3 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:348:in `block (2 levels) in monitor'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `loop'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `block in monitor'
>   ~/Apps/saw/admin-interface/ext/thread.rb:13:in `block in initialize'
> 2021-12-11 21:50:44 -0300 | WARN    | 127.0.0.1:[27016,27117] Monitor | Time since last server query success: 11s
> 2021-12-11 21:50:46 -0300 | ERROR   | Error while sending RCON | Exception occurred (RuntimeError): 127.0.0.1:27117       Nil response for RCON.
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:228:in `send_receive'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:206:in `block in send_receive_wrapper'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:203:in `send_receive_wrapper'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:326:in `send'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:358:in `get_players_and_bots'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:266:in `do_rcon_query'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:352:in `block (4 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:352:in `block (3 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:348:in `block (2 levels) in monitor'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `loop'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `block in monitor'
>   ~/Apps/saw/admin-interface/ext/thread.rb:13:in `block in initialize'
> 2021-12-11 21:50:46 -0300 | ERROR   | 127.0.0.1:[27016,27117] Monitor | RCON query failed | Exception occurred (RuntimeError): 127.0.0.1:27117       Nil response for RCON.
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:228:in `send_receive'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:206:in `block in send_receive_wrapper'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:203:in `send_receive_wrapper'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:326:in `send'
>   ~/Apps/saw/admin-interface/lib/rcon-client.rb:358:in `get_players_and_bots'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:266:in `do_rcon_query'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:352:in `block (4 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:352:in `block (3 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:348:in `block (2 levels) in monitor'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `loop'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `block in monitor'
>   ~/Apps/saw/admin-interface/ext/thread.rb:13:in `block in initialize'
> 2021-12-11 21:50:46 -0300 | WARN    | 127.0.0.1:[27016,27117] Monitor | Time since last RCON success: 13s
> 2021-12-11 21:50:50 -0300 | WARN    | [127.0.0.1:27016] Couldn't get UDP response (NoUDPResponseError raised)
> 2021-12-11 21:50:50 -0300 | ERROR   | 127.0.0.1:[27016,27117] Monitor | Server query failed | Exception occurred (NoUDPResponseError): Could not read a UDP response from server 127.0.0.1:27016
>   ~/Apps/saw/admin-interface/lib/server-query.rb:28:in `send_recv_udp'
>   ~/Apps/saw/admin-interface/lib/server-query.rb:26:in `send_recv_udp'
>   ~/Apps/saw/admin-interface/lib/server-query.rb:42:in `a2s_info'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:298:in `do_server_query'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:355:in `block (4 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:355:in `block (3 levels) in monitor'
>   ~/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:348:in `block (2 levels) in monitor'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `loop'
>   ~/Apps/saw/admin-interface/lib/server-monitor.rb:347:in `block in monitor'
>   ~/Apps/saw/admin-interface/ext/thread.rb:13:in `block in initialize'
> 2021-12-11 21:50:50 -0300 | WARN    | 127.0.0.1:[27016,27117] Monitor | Time since last server query success: 17s

**Comment by gusarg81** [comment]
I think I´ve found the problem. For some reason 2 configs were running at the same time (is that possible?) when I start insurgency server. So thats why the problem.

**Comment by Joe-Klauza** [comment]
That seems right.

I have seen query stop working on startup occasionally, but it is fixed by server restart. If it's persistently down that might mean there is an issue with the GSLT being expired.

**Comment by gusarg81** [comment]
I doble check that (GSLT) and restart the server many times, but when I change Default map to originals maps from the game, does work. So, the problems seems to be when I select a custom map as Default map.
