### ISSUE TITLE
Installation on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by msachtl** [Joe-Klauza/sandstorm-admin-wrapper#126]
Hello, I tried to install the wrapper on Ubuntu 22.04 lts which is shipped with openssl 3.0.
The wrapper installation failed at the installation of the openssl 2.2.0 ruby gem. 
After some experiments I was able to fix the problem basically by replacing the openssl version in the Gemfile.lock. 
You may want to include the changes in your next release.
Please find attached my changed files. 
[wrapper.zip](https://github.com/Joe-Klauza/sandstorm-admin-wrapper/files/9333785/wrapper.zip)
 
Kind Regards

Marc Sachtleber

**Comment by Joe-Klauza** [comment]
Hi, please submit your changes as a pull request rather than a ZIP file.
