### ISSUE TITLE
Unable to open the config page Receiving below error. 

### ISSUE THREAD

**Issue by cartman-sp69** [Joe-Klauza/sandstorm-admin-wrapper#127]
An error occurred (Errno::ENOENT). Only hosts can see the following message and backtrace: No such file or directory @ rb_sysopen - D:/sandstorm-admin-wrapper-1.0.0/server-config/0a361a62-c9cc-4e7c-8463-693d927cf1f5/Game.ini | Backtrace:
lib/webapp.rb:739:in `read'
lib/webapp.rb:739:in `block in <class:SandstormAdminWrapperSite>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1684:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1684:in `block in compile!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1002:in `block (3 levels) in route!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1020:in `route_eval'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1002:in `block (2 levels) in route!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1051:in `block in process_route'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1049:in `catch'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1049:in `process_route'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1000:in `block in route!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:997:in `each'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:997:in `route!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1121:in `block in dispatch!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1092:in `catch'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1092:in `invoke'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1116:in `dispatch!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:932:in `block in call!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1092:in `catch'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1092:in `invoke'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:932:in `call!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:921:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-protection-3.0.2/lib/rack/protection/xss_header.rb:20:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-protection-3.0.2/lib/rack/protection/base.rb:53:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-protection-3.0.2/lib/rack/protection/base.rb:53:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-protection-3.0.2/lib/rack/protection/path_traversal.rb:18:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-protection-3.0.2/lib/rack/protection/json_csrf.rb:28:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-protection-3.0.2/lib/rack/protection/base.rb:53:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-protection-3.0.2/lib/rack/protection/base.rb:53:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-protection-3.0.2/lib/rack/protection/frame_options.rb:33:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/null_logger.rb:11:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:219:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1995:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1554:in `block in call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1770:in `synchronize'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sinatra-3.0.2/lib/sinatra/base.rb:1554:in `call'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/handler/webrick.rb:95:in `service'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'

**Comment by Joe-Klauza** [comment]
Be sure to use the default (just press enter) at this prompt (and a subsequent prompt) when installing Ruby with the MSYS2 and MINGW development toolchain: 
![image](https://user-images.githubusercontent.com/13367199/202817643-9421ab8e-3794-4194-acbb-6b677d21f13c.png)

**Comment by cartman-sp69** [comment]
I have done that tried it Twice will try it again

**Comment by cartman-sp69** [comment]
So the Server-Config Folder is empty no files are created there if i manually add all the required files I can open the page but no settings will save

**Comment by cartman-sp69** [comment]
Got everything working but unable to join or see the server ports are open cannot even connect to loopback ip

**Comment by Joe-Klauza** [comment]
SAW is supposed to write these files on startup (see https://github.com/Joe-Klauza/sandstorm-admin-wrapper/blob/79d0c597a295245ecd2360e4640ec065db67e8f2/admin-interface/lib/config-handler.rb#L602). Other than the MSYS2 and MINGW development toolchain install and OS permissions issues, I am unsure why these files are not being created and no errors about file creation are being logged.
