### ISSUE TITLE
Please Fix Mods Support by adding GameUserSettings.ini

### ISSUE THREAD

**Issue by Krazypoloc** [Joe-Klauza/sandstorm-admin-wrapper#129]
As of the Update 1.11 Operation: Warlord - Steam Hotfix #5, Insurgency: Sandstorm no longer uses the Engine.ini to store the mod.io access token which is now in the GameUserSettings.ini. Every server provider that was using the Engine.ini needs to be informed of this ASAP and the admin guide updated.

https://steamcommunity.com/app/581320/discussions/0/4510921146048002669/

**Comment by Joe-Klauza** [comment]
Hi @Krazypoloc. SAW has had this since version https://github.com/Joe-Klauza/sandstorm-admin-wrapper/releases/tag/v0.17.0-beta released in February.

![image](https://user-images.githubusercontent.com/13367199/207939660-5efa3afe-b1d3-4514-b06a-c0e8695b78f9.png)

**Comment by Krazypoloc** [comment]
Works a treat thanks @Joe-Klauza .
