### ISSUE TITLE
Webserver fails on default 51422, all other ports cause issues with webrick

### ISSUE THREAD

**Issue by AfterLemon** [Joe-Klauza/sandstorm-admin-wrapper#133]
> Bundling
> Using bcrypt 3.1.18
> Using bindata 2.4.14
> Using bundler 2.3.7
> Using citrus 3.0.2
> Using coderay 1.1.3
> Using ffi 1.15.5
> Using sync 0.5.0
> Using tins 1.31.1
> Using file-tail 1.2.0
> Using geocoder 1.8.1
> Using inifile 3.0.0
> Using method_source 1.0.0
> Using ruby2_keywords 0.0.5
> Using mustermann 3.0.0
> Using oj 3.13.23
> Using openssl 3.0.1
> Using pry 0.14.1
> Using rack 2.2.6.4
> Using rack-protection 3.0.4
> Using rubyzip 2.3.2
> Using tilt 2.0.11
> Using sinatra 3.0.4
> Using sys-proctable 1.2.7
> Using sysrandom 1.0.5
> Using toml-rb 2.2.0
> Using unicode-display_width 2.3.0
> Using webrick 1.7.0
> Bundle complete! 15 Gemfile dependencies, 27 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
> Starting webapp
> 2023-04-07 19:41:32 -0400 | INFO    | Setting webserver root dir to: X:/sandstorm-admin-wrapper/admin-interface/docroot
> 2023-04-07 19:41:32 -0400 | INFO    | WEBrick 1.7.0
> 2023-04-07 19:41:32 -0400 | INFO    | ruby 3.2.1 (2023-02-08) [x64-mingw-ucrt]
> 2023-04-07 19:41:32 -0400 | ERROR   | Exception caused webserver exit | Exception occurred (Errno::EACCES): Permission denied - bind(2) for 127.0.0.1:51422
>   D:/Ruby32-x64/lib/ruby/3.2.0/socket.rb:205:in `bind'
>   D:/Ruby32-x64/lib/ruby/3.2.0/socket.rb:205:in `listen'
>   D:/Ruby32-x64/lib/ruby/3.2.0/socket.rb:768:in `block in tcp_server_sockets'
>   D:/Ruby32-x64/lib/ruby/3.2.0/socket.rb:231:in `each'
>   D:/Ruby32-x64/lib/ruby/3.2.0/socket.rb:231:in `foreach'
>   D:/Ruby32-x64/lib/ruby/3.2.0/socket.rb:766:in `tcp_server_sockets'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:60:in `create_listeners'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/ssl.rb:165:in `listen'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:111:in `initialize'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:47:in `initialize'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.6.4/lib/rack/handler/webrick.rb:38:in `new'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.6.4/lib/rack/handler/webrick.rb:38:in `run'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.6.4/lib/rack/server.rb:327:in `start'
>   lib/webapp.rb:1380:in `<main>'
> 2023-04-07 19:41:32 -0400 | INFO    | Webserver stopped
> 2023-04-07 19:41:32 -0400 | INFO    | Config written
> Error level: 1

The error when running on another port (by editing config.toml 51422 -> 61422)

> Bundling
> Using bcrypt 3.1.18
> Using bindata 2.4.14
> Using bundler 2.3.7
> Using citrus 3.0.2
> Using coderay 1.1.3
> Using ffi 1.15.5
> Using sync 0.5.0
> Using tins 1.31.1
> Using file-tail 1.2.0
> Using geocoder 1.8.1
> Using inifile 3.0.0
> Using method_source 1.0.0
> Using ruby2_keywords 0.0.5
> Using mustermann 3.0.0
> Using oj 3.13.23
> Using openssl 3.0.1
> Using pry 0.14.1
> Using rack 2.2.6.4
> Using rack-protection 3.0.4
> Using rubyzip 2.3.2
> Using tilt 2.0.11
> Using sinatra 3.0.4
> Using sys-proctable 1.2.7
> Using sysrandom 1.0.5
> Using toml-rb 2.2.0
> Using unicode-display_width 2.3.0
> Using webrick 1.7.0
> Bundle complete! 15 Gemfile dependencies, 27 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
> Starting webapp
> 2023-04-07 19:43:32 -0400 | INFO    | Setting webserver root dir to: X:/sandstorm-admin-wrapper/admin-interface/docroot
> 2023-04-07 19:43:32 -0400 | INFO    | WEBrick 1.7.0
> 2023-04-07 19:43:32 -0400 | INFO    | ruby 3.2.1 (2023-02-08) [x64-mingw-ucrt]
> 2023-04-07 19:43:32 -0400 | INFO    |
> Certificate:
> 2023-04-07 19:43:32 -0400 | INFO    | WEBrick::HTTPServer#start: pid=17984 port=61422
> 2023-04-07 19:43:33 -0400 | INFO    | Webserver initialized! Visit: https://127.0.0.1:61422
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63856 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63857 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63858 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63859 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63860 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63861 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63862 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63863 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63864 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'
> 2023-04-07 19:43:37 -0400 | ERROR   | SSL_accept returned=1 errno=0 peeraddr=127.0.0.1:63865 state=error: http request
> 2023-04-07 19:43:37 -0400 | ERROR   | Backtrace:
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `accept'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:302:in `block (2 levels) in start_thread'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/utils.rb:258:in `timeout'
>   D:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:300:in `block in start_thread'

**Comment by AfterLemon** [comment]
Issue continued after a reboot. Issue also continued after re-downloading the wrapper and copying SteamCMD installation folder to the new location.

Setting:
`admin_interface_use_ssl = true -> false`

Seems to fix the issue.

**Comment by Joe-Klauza** [comment]
@AfterLemon I highly recommend leaving `use_ssl` enabled, especially if SAW is accessed over a network, else all communications including passwords will be sent in plain text.

The error you show: ` Exception occurred (Errno::EACCES): Permission denied - bind(2) for 127.0.0.1:51422` indicates the user does not have access to bind that port. Perhaps Windows Firewall or another program is not allowing it.

**Comment by AfterLemon** [comment]
Confirmed that the first issue (binding port 51422 was solved with a look at the firewall and a restart of windows.

The second issue remains when re-enabling `use_ssl`.

**Comment by Joe-Klauza** [comment]
For the second error, make sure you are prefixing `https://` protocol in your browser when connecting.

**Comment by AfterLemon** [comment]
I feel bad even wasting your time on this issue. Connecting via `127.0.0.1` does not automatically prepend `https://` even when the browser is set to always use https. Previously I was using `localhost` which does get prepended.

Apologies and thank you!
