### ISSUE TITLE
RCON does not connect past initial message

### ISSUE THREAD

**Issue by AfterLemon** [Joe-Klauza/sandstorm-admin-wrapper#134]
Disabling 'Hang Recovery' allows the game server to continue, but the wrapper continues to throw errors after every retry.
Disabling RCON allows the server to run with provided settings, but offers no control over the game.

This was an issue before the most recent update.

> Bundling
> Using bcrypt 3.1.18
> Using bindata 2.4.14
> Using bundler 2.3.7
> Using citrus 3.0.2
> Using coderay 1.1.3
> Using ffi 1.15.5
> Using sync 0.5.0
> Using tins 1.31.1
> Using file-tail 1.2.0
> Using geocoder 1.8.1
> Using inifile 3.0.0
> Using method_source 1.0.0
> Using ruby2_keywords 0.0.5
> Using mustermann 3.0.0
> Using oj 3.13.23
> Using openssl 3.0.1
> Using pry 0.14.1
> Using rack 2.2.6.4
> Using rack-protection 3.0.4
> Using rubyzip 2.3.2
> Using tilt 2.0.11
> Using sinatra 3.0.4
> Using sys-proctable 1.2.7
> Using sysrandom 1.0.5
> Using toml-rb 2.2.0
> Using unicode-display_width 2.3.0
> Using webrick 1.7.0
> Bundle complete! 15 Gemfile dependencies, 27 gems now installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.
> Starting webapp
> 2023-04-08 01:41:35 -0400 | INFO    | Setting webserver root dir to: X:/sandstorm-admin-wrapper/admin-interface/docroot
> 2023-04-08 01:41:35 -0400 | INFO    | WEBrick 1.7.0
> 2023-04-08 01:41:35 -0400 | INFO    | ruby 3.2.1 (2023-02-08) [x64-mingw-ucrt]
> 2023-04-08 01:41:35 -0400 | INFO    | WEBrick::HTTPServer#start: pid=25328 port=51422
> 2023-04-08 01:41:36 -0400 | INFO    | Webserver initialized! Visit: http://127.0.0.1:51422
> 2023-04-08 01:41:50 -0400 | INFO    | IP: 127.0.0.1 | admin [host] logged in (ca4a6982-d62d-4763-8e21-983dce19357b)
> 2023-04-08 01:42:51 -0400 | INFO    | Initializing daemon with config ID a1f75e9d-f347-441d-900f-34ac63436d13
> 2023-04-08 01:42:51 -0400 | INFO    | [PID (N/A) Ports 27102,27131,27015] | Starting server
> 2023-04-08 01:42:51 -0400 | INFO    | [PID (N/A) Ports 27102,27131,27015] | Spawning game process: ["X:/sandstorm-admin-wrapper/sandstorm-server/Insurgency/Binaries/Win64\\InsurgencyServer-Win64-Shipping.exe", "Precinct?Scenario=Scenario_Precinct_Checkpoint_Insurgents?MaxPlayers=5?Game=Checkpoint?Mutators=FullyLoaded,LockedAim?Lighting=Day", "-Hostname=AfterLemon's Server", "-MaxPlayers=5", "-Port=27102", "-QueryPort=27131", "-log=a1f75e9d-f347-441d-900f-34ac63436d13.log", "-LogCmds=LogGameplayEvents Log", "-LOCALLOGTIMES", "-AdminList=Admins", "-MapCycle=MapCycle", "-mutators=FullyLoaded,LockedAim", 
> 2023-04-08 01:42:51 -0400 | INFO    | [PID 22028 Ports 27102,27131,27015] | Game process spawned. Starting self-monitoring after detecting RCON listening message.
> 2023-04-08 01:42:56 -0400 | INFO    | [PID 22028 Ports 27102,27131,27015] | RCON listening - Ending server start/stop lock
> 2023-04-08 01:43:05 -0400 | ERROR   | Error while sending RCON | Exception occurred (RuntimeError): 127.0.0.1:27015       Nil response for RCON.
>   X:/sandstorm-admin-wrapper/admin-interface/lib/rcon-client.rb:228:in `send_receive'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/rcon-client.rb:206:in `block in send_receive_wrapper'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/rcon-client.rb:102:in `synchronize'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/rcon-client.rb:203:in `send_receive_wrapper'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/rcon-client.rb:326:in `send'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/rcon-client.rb:358:in `get_players_and_bots'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/server-monitor.rb:266:in `do_rcon_query'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/server-monitor.rb:361:in `block (4 levels) in monitor'
>   D:/Ruby32-x64/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/server-monitor.rb:361:in `block (3 levels) in monitor'
>   D:/Ruby32-x64/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/server-monitor.rb:357:in `block (2 levels) in monitor'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/server-monitor.rb:356:in `loop'
>   X:/sandstorm-admin-wrapper/admin-interface/lib/server-monitor.rb:356:in `block in monitor'
>   X:/sandstorm-admin-wrapper/admin-interface/ext/thread.rb:13:in `block in initialize'
> 2023-04-08 01:43:05 -0400 | ERROR   | 127.0.0.1:[27131,27015] Monitor | RCON query failed | Exception occurred (RuntimeError): 127.0.0.1:27015       Nil response for RCON.

**Comment by AfterLemon** [comment]
Want to add, I was able to find the pack slice issue in my own copy a few weeks ago, but I am still having issues with RCON.

**Comment by Joe-Klauza** [comment]
Hi @AfterLemon. I have two potential causes:
1. The port issue you are having in #133 may be affecting the server's ability to bind the RCON port
2. Try regenerating the RCON password. I think it is possible that it generates an invalid character or length, leading to issues (some have reported this as a fix for RCON connection issues).

**Comment by AfterLemon** [comment]
1. It's possible there is an issue with binding the RCON port, but the port issue from #133 seems to be solved after a restart. Are there required firewall settings for the RCON port? What port does it use?

2. I just tried regenerating the RCON password, but received the same error. Is this something I can remove to see if it works at all?

**Comment by Joe-Klauza** [comment]
1. The server uses RCON over TCP at the port defined in SAW/Game.ini (27015 by default if memory serves). You may have to allow the server shipping executable access to this port in the firewall.
2. You might try typing in your own basic password to check for issues with characters/length.

**Comment by AfterLemon** [comment]
1. Default 27015 port is set for RCON. That port is opened in firewall for both TCP and UDP, I have added the server exe and BootstrapPackagedGame to my firewall. Neither helped.
2. I set the password to something very simple and had no success either.

**Comment by Joe-Klauza** [comment]
I recommend reviewing the server log for any lines containing the RCON port number or `LogRcon`; maybe that will give us more information to help troubleshoot.

It is possible this port is already bound by another process; this can be checked in Resource Monitor -> Network tab -> Listening Ports section. You can also check the firewall status for the port here if/when it is bound by the server.

**Comment by AfterLemon** [comment]
That's exactly the issue. "AppleMobileDeviceProcess.exe" is using port 27015 (apparently by default)

On knowing that from Resource Monitor, this Apple response makes a lot more sense in the logs.
Thank you, this is also solved. Everything is working fully.

> 2023-04-08 01:43:01 -0400 | DEBUG   | Opening socket to 127.0.0.1:27015
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Authenticating RCON connection
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Attempting to gain mutex lock
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Sucessfully gained mutex lock
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Sending packet: REDACTED
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Receiving response
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Header: "&\x01\x00\x00\x01\x00\x00\x00\b\x00\x00\x00"
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Unpacked header: Size - 294 | ID - 1 | Type - 8
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Reading 294 (+2) bytes
> 2023-04-08 01:43:01 -0400 | DEBUG   | 127.0.0.1:27015       Read initial response: "D7QU<xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>MessageType</key>\n\t<string>Result</string>\n\t<key>Number</key>\n\t<integer>1</integer>\n</dict>\n</plist"
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Additional header: nil
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Response: "D7QU<xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>MessageType</key>\n\t<string>Result</string>\n\t<key>Number</key>\n\t<integer>1</integer>\n</dict>\n</plist"
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Got response: "D7QU<xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>MessageType</key>\n\t<string>Result</string>\n\t<key>Number</key>\n\t<integer>1</integer>\n</dict>\n</plist"
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Ending mutex lock
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Successfully authenticated.
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Attempting to gain mutex lock
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Sucessfully gained mutex lock
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Sending packet: "\x15\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00listplayers\x00\x00"
> 2023-04-08 01:43:03 -0400 | DEBUG   | 127.0.0.1:27015       Receiving response

**Comment by Joe-Klauza** [comment]
Woohoo! Enjoy your new server(s)!
