### ISSUE TITLE
Failed server config

### ISSUE THREAD

**Issue by AndreyBoyarshinov** [Joe-Klauza/sandstorm-admin-wrapper#136]
An error occurred (NoMethodError). Only hosts can see the following message and backtrace: undefined method `[]' for nil:NilClass | Backtrace:
F:/SteamLibrary/steamapps/common/sandstorm-admin-wrapper-master/admin-interface/lib/config-handler.rb:599:in `block in init_server_config_files'
F:/SteamLibrary/steamapps/common/sandstorm-admin-wrapper-master/admin-interface/lib/config-handler.rb:598:in `each'
F:/SteamLibrary/steamapps/common/sandstorm-admin-wrapper-master/admin-interface/lib/config-handler.rb:598:in `init_server_config_files'
lib/webapp.rb:738:in `block in <class:SandstormAdminWrapperSite>'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1691:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1691:in `block in compile!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1009:in `block (3 levels) in route!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1027:in `route_eval'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1009:in `block (2 levels) in route!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1058:in `block in process_route'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1056:in `catch'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1056:in `process_route'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1007:in `block in route!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1004:in `each'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1004:in `route!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1128:in `block in dispatch!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1099:in `catch'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1099:in `invoke'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1123:in `dispatch!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:939:in `block in call!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1099:in `catch'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1099:in `invoke'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:939:in `call!'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:928:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-protection-3.0.4/lib/rack/protection/xss_header.rb:20:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-protection-3.0.4/lib/rack/protection/base.rb:53:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-protection-3.0.4/lib/rack/protection/base.rb:53:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-protection-3.0.4/lib/rack/protection/path_traversal.rb:18:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-protection-3.0.4/lib/rack/protection/json_csrf.rb:28:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-protection-3.0.4/lib/rack/protection/base.rb:53:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-protection-3.0.4/lib/rack/protection/base.rb:53:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-protection-3.0.4/lib/rack/protection/frame_options.rb:33:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:266:in `context'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:260:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.6.4/lib/rack/null_logger.rb:11:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:219:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:2002:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1561:in `block in call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1777:in `synchronize'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/sinatra-3.0.4/lib/sinatra/base.rb:1561:in `call'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/rack-2.2.6.4/lib/rack/handler/webrick.rb:95:in `service'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'

**Comment by AndreyBoyarshinov** [comment]
@Joe-Klauza Good afternoon I tried your advice, did a completely clean install, to a different directory, but unfortunately I got exactly the same error. Can you recommend other options?

**Comment by Joe-Klauza** [comment]
I would recommend reviewing the install of Ruby to ensure you are installing with devkit and choosing the default options when running the MSYS install portion of it.

**Comment by AndreyBoyarshinov** [comment]
Tried. Ruby with devkit and subsequent installation of MSYS. Thanks for the tips, I'm looking for other solutions)

**Comment by Latte1995** [comment]
I got same problem.May I ask if you have solved this problem?

**Comment by AndreyBoyarshinov** [comment]
Nope  :(

**Comment by Joe-Klauza** [comment]
@AndreyBoyarshinov @Latte1995 I think I may have fixed this in the [latest release (v1.0.10)](https://github.com/Joe-Klauza/sandstorm-admin-wrapper/releases/tag/v1.0.10). Do you mind testing this for confirmation?
