### ISSUE TITLE
Request - Windows OS - auto start servers

### ISSUE THREAD

**Issue by TheRecliner** [Joe-Klauza/sandstorm-admin-wrapper#91]
Hello, so far this is an awesome console you made, and I will be donating when I have some money. I wanted to see if there is already a way, or if there can be a way for when the server restarts (power outage or something), that the servers it hosts will auto start? I dont see anything in the web page, but maybe I have missed it?

Maybe there is a command line to put into a startup task?

Thanks!

**Comment by Joe-Klauza** [comment]
Hi, @TheRecliner! You should be able to make a task in Windows `Task Scheduler` which calls `windows_start.bat` with the `-s` parameter to start whichever servers you like. For example, if you had two servers to start whose configs are named `Config 1` and `Config 2`, you'd have the task execute:
```
windows_start.bat -s "Config 1" -s "Config 2"
```

**Comment by TheRecliner** [comment]
Awesome! I already had it starting that bat file, just wasn't sure about
the rest. Thanks!
