### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by dutchxarms** [Joe-Klauza/sandstorm-admin-wrapper#93]
Have crashing server running without wrapper it will not crash
with wrapper it will randomly restart server for no good reason

**Comment by Joe-Klauza** [comment]
I'm going to need more information to diagnose your server crashes. Server logs, SAW logs, etc.

**Comment by dutchxarms** [comment]
ok i will. when it crashes again i will send you all of it here.

**Comment by Joe-Klauza** [comment]
Keep in mind this is a public issue tracker and these logs contain private information (passwords, GSLT, IP and port combinations, user IDs and IPs). It would be unwise to share the unedited logs here.
