### ISSUE TITLE
query port issue

### ISSUE THREAD

**Issue by liucin** [Joe-Klauza/sandstorm-admin-wrapper#96]
waht does "query status" means? I mean it always red when I start the server and query port game port is open. Everything is ok, but I just cannot find my server in the goddamn game. Thanks for your help.

**Comment by Joe-Klauza** [comment]
Sounds like something else might be listening at the port you're using for server queries. This would also be why you can't find your server in the game. Try changing the query port in the server config.

**Comment by liucin** [comment]
I was just tyring to change the port, which seems not work out. I also check the log SAAW saved. It said that server's UDP response could not be read or something, could you help me to explain it? The following was part of SAAW log.







------------------ 原始邮件 ------------------
发件人:&nbsp;"Joe Klauza"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 凌晨2:46
收件人:&nbsp;"Joe-Klauza/sandstorm-admin-wrapper"<sandstorm-admin-wrapper@noreply.github.com&gt;;
抄送:&nbsp;"lingered"<1647489141@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Joe-Klauza/sandstorm-admin-wrapper] query port issue (#96)





 
Sounds like something else might be listening at the port you're using for server queries. This would also be why you can't find your server in the game. Try changing the query port in the server config.

**Comment by Joe-Klauza** [comment]
Looks like the logs aren't included; I don't see anything.

**Comment by liucin** [comment]
Alright, thank you.



---Original---

**Comment by Joe-Klauza** [comment]
@liucin I'm going to close this issue. If you want to talk about it in Discord or send me some logs, join us [here](https://discord.gg/DSwnmyA).

**Comment by liucin** [comment]
Fine, I will if I find something helpful.



---Original---
