### ISSUE TITLE
Incorrect Max Players with ModScenarios

### ISSUE THREAD

**Issue by Doom701** [Joe-Klauza/sandstorm-admin-wrapper#97]
Goal: Getting the server to start on a mod map. 
After updating ModScenarios.txt with many different variations and changing the Default Map option accordingly. The server always starts with the incorrect max players showing in the game server list. Should be 8 but is showing 32. 
Is this an issue or am I doing something incorrect?

**Tried with the following in ModScenarios.txt:**
- Wolf-land
- Scenario_Wolf-land
- Scenario_Wolf-land_Checkpoint
- OperationRedwood
- Scenario_OperationRedwood

 Running SAW on Windows 10 Pro 64 Bit 

_If you need any additional information, just let me know._

**Comment by Joe-Klauza** [comment]
Thanks for the report! Should be fixed in [v0.12.1-beta](https://github.com/Joe-Klauza/sandstorm-admin-wrapper/releases/tag/v0.12.1-beta).
