### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by Doom701** [Joe-Klauza/sandstorm-admin-wrapper#98]
I'm not sure what causes this issue. Ever so often when I start a monitor on an external server and go to the status page, I get the following errors on my page.
Page Error: https://pastebin.com/ZmgKkWZ8
CMD Log: https://pastebin.com/UzZUX9AJ
[sandstorm-admin-wrapper.log](https://github.com/Joe-Klauza/sandstorm-admin-wrapper/files/4430625/sandstorm-admin-wrapper.log)

Also I get the following error spammed in my cmd when I restart.
2020-04-03 22:20:57 -0400 | WARN    | IP: 108.162.241.14 | User unauthorized: [logged out] requesting user-privileged content: /server-list

**Comment by Joe-Klauza** [comment]
> Also I get the following error spammed in my cmd when I restart.

You need to set a session secret in Wrapper Config to have sessions persist over restart; `User unauthorized` means you need to refresh and log in (assuming that is your IP). Redirects to the login page currently aren't great, leading to a lot of background requests spamming your log with that message. I need a better solution for this in the future.

The issues you've posted logs for is a legitimate issue as a result of me forgetting that server monitors can be used independently of local servers. I should have some fix[es] for this in `v0.12.3-beta` today.

For future issues, I recommend joining [our community server hosts Discord](https://discord.gg/DSwnmyA) to send me logs directly via private message there, as they can contain sensitive information that you might not want publicly accessible on GitHub.

**Comment by Joe-Klauza** [comment]
@Doom701 should be closed by [v0.12.3-beta](https://github.com/Joe-Klauza/sandstorm-admin-wrapper/releases/tag/v0.12.3-beta). Feel free to reopen if you still have issues.
